### ISSUE TITLE
Property Listing Block Improvements

### ISSUE THREAD

**Issue by bstopp** [hlxsites/hsf-commonmoves#108]
The property listing block causes PSI score issues and this needs to be remedied.

It also needs to support more options, full required list:

- [ ] Map/Bounding box
- [ ] Radius from center point
- [ ] Listing type Author support - rent, sale, pending, sold
- [ ] Property type Author support - commerical, single family, condo, farm, etc.

**Comment by irenelagno** [comment]
- a couple of issues I faced while integrating property-listing cards.
1. add loader on property loaded
2. dynamic block height if the search result is less than the desired total amount (2 instead of 8)
see 
<img width="776" alt="Screen Shot 2023-05-19 at 4 19 43 PM" src="https://github.com/hlxsites/hsf-commonmoves/assets/7125318/ff43b1d1-5f5c-4b44-8ec8-e9d9a31af52e">

you can play with the search on the link from my PR:
https://result-page--hsf-commonmoves--hlxsites.hlx.page/search
